export const LANDING_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const COMPANY_ROUTE = '/company'
export const CASES_ROUTE = '/cases'
export const AUTH_ROUTE = '/auth'
export const PROFILE_ROUTE = '/profile'
export const NOTIFY_ROUTE = '/notify'
export const PORTFOLIO_ROUTE = '/portfolio'